ud

diff --git a/build/run b/build/run
--- a/build/run
+++ b/build/run
@@ -10,10 +10,19 @@ else
     cmake ..
 fi
 
-make
+# re-build the kernel
+cd ../src
+asm6809 -H -9 "kernel_f000.asm" -o "../build/kernel_f000.hex" -l "../build/kernel_f000.lst" -s "../build/kernel_f000.sym"    
 if [ $? -eq 0 ]; then
-    ./main
+    cd ../build
+    make
+    if [ $? -eq 0 ]; then
+        ./main
+    else
+        echo "\e[31mmake FAILED to build!\e[0m"
+    fi
 else
-    echo "\e[31mmake FAILED to build!\e[0m"
+    echo "\e[31masm6809 FAILED!\e[0m"
 fi
+
 
